<?php
/**
 * Magnetism & Accretion 2023 Theme functions and definitions
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package Magnetism & Accretion 2023
 * @since 1.0.0
 */

/**
 * Define Constants
 */
define( 'CHILD_THEME_MAGNETISM_ACCRETION_2023_VERSION', '1.0.0' );

/**
 * Enqueue styles
 */
function child_enqueue_styles() {

	wp_enqueue_style( 'magnetism-accretion-2023-theme-css', get_stylesheet_directory_uri() . '/style.css', array('astra-theme-css'), CHILD_THEME_MAGNETISM_ACCRETION_2023_VERSION, 'all' );

}

/**
 * Makw JWT helper functiona available.
 */
include(dirname(__FILE__).'/php-jwt/jwt.php');

add_action( 'wp_enqueue_scripts', 'child_enqueue_styles', 15 );

/**
 * Use custom text for "Other" option in Gravity Forms.
 */
add_filter( 'gform_other_choice_value', function( $value, $field ) {
    return 'I\'d rather specify my own';
    }, 10, 2 );

function ma2023_payment_form($userId, $name, $amount) {
    $merchantId = ma2023_get_theme_option("adumo_merchant_id");
    $applicationId = ma2023_get_theme_option("adumo_application_id");
    $merchantReference = "MA2023-USER-" . $userId;
    $secretKey = ma2023_get_theme_option("adumo_secret_key");
    $currency = ma2023_get_theme_option("adumo_currency");

    // Create the JWT
    $payloadArray = array();
    $payloadArray['cuid'] = $merchantId;
    $payloadArray['auid'] = $applicationId;
    $payloadArray['amount'] = $amount;
    $payloadArray['mref'] = $merchantReference;
    $payloadArray['jti'] = base64_encode(random_bytes (32));
    $payloadArray['iat'] = time() - 60;
    $payloadArray['exp'] = time() + 600;
    //$token = JWT::encode($payloadArray, $secretKey);
    $token = "";

    return '
    <FORM name="Post" action="' . ma2023_get_theme_option("adumo_payment_url") . '" method="post">
    <!-- Mode value 0 indicates that this is in Test Mode. Change the value to 1 for Live Mode. -->
    <input type="hidden" name="Mode" value="1">
    <input type="hidden" name="MerchantID" value="' . $merchantId . '">
    <input type="hidden" name="ApplicationID" value="' . $applicationId . '">
    <input type="hidden" name="MerchantReference" value="' . $merchantReference . '">
    <input type="hidden" name="Amount" value="' . $amount . '"></label>
    <!-- Token must be generated by the merchant for each transaction, the below token is only valid for this transaction -->
    <input type="hidden" name="Token" value="' . $token . '">
    <input type="hidden" name="txtCurrencyCode" value="' . $currency . '">
    <input type="hidden" name="RedirectSuccessfulURL" value="' . ma2023_get_theme_option("redirect_successful_url") . '">
    <input type="hidden" name="RedirectFailedURL" value="' . ma2023_get_theme_option("redirect_failed_url") . '">
    <!-- Additional variables for that can be populated by the merchant -->
    <input type="hidden" name="Variable1" value="Delivery">
    <input type="hidden" name="Variable2" value=""></label><br>
    <!-- First items details for clients -->
    <input type="hidden" name="Qty1" value="1">
    <input type="hidden" name="ItemRef1" value="MA2023">
    <input type="hidden" name="ItemDescr1" value="Magnetism & Accretion 2023">
    <input type="hidden" name="ItemAmount1" value="1">
    <!-- Additional details for the purchased items -->
    <input type="hidden" name="ShippingCost" value="0.00">
    <input type="hidden" name="Discount" value="0.00">
    <!-- Fields for Clients Shipping Details -->
    <input type="hidden" name="Recipient" value="' . $surname . '"></label><br>
    <input type="hidden" name="ShippingAddress1" value="n/a">
    <input type="hidden" name="ShippingAddress2" value="n/a">
    <input type="hidden" name="ShippingAddress3" value="n/a">
    <input type="hidden" name="ShippingAddress4" value="n/a">
    <input type="hidden" name="ShippingAddress5" value="n/a">
    <input type="submit" value="Pay ' . $currency . ' ' . $amount . '" id="virtualPost">
    </FORM>
    ';
}

add_shortcode( 'payment', function () {
    // Ensure the necessary details were provided
    if (!$_GET["userId"]) {
        return '<div>The user id is missing. Please use the payment link you were sent.</div>';
    }
    if (!$_GET["surname"]) {
        return '<div>The surname is missing. Please use the payment link you were sent.</div>';
    }
    if (!$_GET["amount"]) {
        return '<div>The amount is missing. Please use the payment link you were sent.</div>';
    }

    // Sanitize the input
    $userId = filter_var($_GET["userId"], FILTER_SANITIZE_NUMBER_INT);
    $surname = filter_var($_GET["surname"], FILTER_SANITIZE_STRING);
    $amount = filter_var($_GET["amount"], FILTER_SANITIZE_NUMBER_INT);

    // Create the payment form
    return ma2023_payment_form($userId, $surname, $amount);
});

/* Adapted from https://www.wpexplorer.com/wordpress-theme-options/ */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Start Class
if ( ! class_exists( 'MA2023_Theme_Options' ) ) {

    class MA2023_Theme_Options {

        /**
        * Start things up
        *
        * @since 1.0.0
        */
    public function __construct() {

            // We only need to register the admin panel on the back-end
    if ( is_admin() ) {
        add_action( 'admin_menu', array( 'MA2023_Theme_Options', 'add_admin_menu' ) );
        add_action( 'admin_init', array( 'MA2023_Theme_Options', 'register_settings' ) );
    }

        }

    /**
    * Returns all theme options
    *
    * @since 1.0.0
    */
    public static function get_adumo_options() {
            return get_option( 'adumo_options' );
        }

    /**
    * Returns single theme option
    *
    * @since 1.0.0
    */
    public static function get_theme_option( $id ) {
            $options = self::get_adumo_options();
            if ( isset( $options[$id] ) ) {
                return $options[$id];
            }
        }

    /**
    * Add sub menu page
    *
    * @since 1.0.0
    */
    public static function add_admin_menu() {
            add_menu_page(
                    esc_html__( 'Adumo Settings', 'text-domain' ),
                    esc_html__( 'Adumo Settings', 'text-domain' ),
                    'manage_options',
                    'adumo-settings',
                    array( 'MA2023_Theme_Options', 'create_admin_page' )
            );
        }

    /**
    * Register a setting and its sanitization callback.
    *
    * We are only registering 1 setting so we can store all options in a single option as
    * an array. You could, however, register a new setting for each option
    *
    * @since 1.0.0
    */
    public static function register_settings() {
            register_setting( 'adumo_options', 'adumo_options', array( 'MA2023_Theme_Options', 'sanitize' ) );
        }

    /**
    * Sanitization callback
    *
    * @since 1.0.0
    */
    public static function sanitize( $options ) {

            // If we have options lets sanitize them
    if ( $options ) {

        // Checkbox
    if ( ! empty( $options['checkbox_example'] ) ) {
        $options['checkbox_example'] = 'on';
    } else {
        unset( $options['checkbox_example'] ); // Remove from options if not checked
    }

    // Input
    if ( ! empty( $options['input_example'] ) ) {
        $options['input_example'] = sanitize_text_field( $options['input_example'] );
    } else {
        unset( $options['input_example'] ); // Remove from options if empty
    }

    // Select
    if ( ! empty( $options['select_example'] ) ) {
        $options['select_example'] = sanitize_text_field( $options['select_example'] );
    }

    }

    // Return sanitized options
    return $options;

        }

    /**
    * Settings page output
    *
    * @since 1.0.0
    */
    public static function create_admin_page() { ?>

    <div class="wrap">

    <h1><?php esc_html_e( 'Adumo Options', 'text-domain' ); ?></h1>

                                                   <p>The various settings are:</p>
                                                   <ul>
                                                   <li>Currency. The currency, such as ZAR or EUR.</li>
                                                   <li>Merchant id. You can get your merchant id by logging into your merchant portal at https://portal.adumoonline.com/login.</li>
                                                   <li>Application id. You can get your application id by logging into your merchant portal at https://portal.adumoonline.com/login.</li>
                                                   <li>Secret key. Your secret key to securly unpack the JWT token, this is configured in the Adumo Online Merchant Portal</li>
                                                   <li>Payment URL. For testing this is https://staging-apiv2.adumoonline.com/product/payment/v1/initialisevirtual; for production it is https://apiv2.adumoonline.com/product/payment/v1/initialisevirtual.</li>
                                                   <li>Redirect successful URL. URL to which the user is redirected after a successful payment.</li>
                                                   <li>Redirect failed URL. URL to which the user is redirected after a failed payment.</li>
                                                   </ul>

                                                   <form method="post" action="options.php">

    <?php settings_fields( 'adumo_options' ); ?>

    <table class="form-table wpex-custom-admin-login-table">

    <?php // Currency ?>
    <tr valign="top">
    <th scope="row"><?php esc_html_e( 'Currency', 'text-domain' ); ?></th>
                              <td>
    <?php $value = self::get_theme_option( 'adumo_currency' ); ?>
    <input type="text" name="adumo_options[adumo_currency]" value="<?php echo esc_attr( $value ); ?>">
                                                                    </td>
                                                                    </tr>

    <?php // Merchant id ?>
    <tr valign="top">
    <th scope="row"><?php esc_html_e( 'Merchant id', 'text-domain' ); ?></th>
                                  <td>
    <?php $value = self::get_theme_option( 'adumo_merchant_id' ); ?>
    <input type="text" name="adumo_options[adumo_merchant_id]" value="<?php echo esc_attr( $value ); ?>">
                                                                </td>
                                                                </tr>

    <?php // Application id ?>
    <tr valign="top">
    <th scope="row"><?php esc_html_e( 'Application id', 'text-domain' ); ?></th>
                                  <td>
    <?php $value = self::get_theme_option( 'adumo_application_id' ); ?>
    <input type="text" name="adumo_options[adumo_application_id]" value="<?php echo esc_attr( $value ); ?>">
                                                                </td>
                                                                </tr>

    <?php // Secret key ?>
    <tr valign="top">
    <th scope="row"><?php esc_html_e( 'Secret key', 'text-domain' ); ?></th>
                                    <td>
    <?php $value = self::get_theme_option( 'adumo_secret_key' ); ?>
    <input type="text" name="adumo_options[adumo_secret_key]" value="<?php echo esc_attr( $value ); ?>">
                                                                       </td>
                                                                       </tr>

    <?php // Payment URL ?>
    <tr valign="top">
    <th scope="row"><?php esc_html_e( 'Payment URL', 'text-domain' ); ?></th>
                                <td>
    <?php $value = self::get_theme_option( 'adumo_payment_url' ); ?>
    <input type="text" name="adumo_options[adumo_payment_url]" value="<?php echo esc_attr( $value ); ?>">
                                                                   </td>

    <?php // Redirect successful URL ?>
    <tr valign="top">
    <th scope="row"><?php esc_html_e( 'Redirect successful URL', 'text-domain' ); ?></th>
                                 <td>
    <?php $value = self::get_theme_option( 'adumo_redirect_successful_url' ); ?>
    <input type="text" name="adumo_options[adumo_redirect_successful_url]" value="<?php echo esc_attr( $value ); ?>">
                                                                    </td>
                                                                    </tr>

    <?php // Redirect failed URL ?>
    <tr valign="top">
    <th scope="row"><?php esc_html_e( 'Redirect failed URL', 'text-domain' ); ?></th>
                                             <td>
    <?php $value = self::get_theme_option( 'adumo_redirect_failed_url' ); ?>
    <input type="text" name="adumo_options[adumo_redirect_failed_url]" value="<?php echo esc_attr( $value ); ?>">
                                                                                </td>
                                                                                </tr>

    </table>

    <?php submit_button(); ?>

    </form>

    </div><!-- .wrap -->
    <?php }

    }
}
new MA2023_Theme_Options();

// Helper function to use in your theme to return a theme option value
function ma2023_get_theme_option( $id = '' ) {
    return MA2023_Theme_Options::get_theme_option( $id );
}